
project_id = "zzcgtdjsmjpfppglcgsm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.create-payment]
verify_jwt = true
[functions.verify-payment]
verify_jwt = true
[functions.cinetpay-webhook]
verify_jwt = false
